### ISSUE TITLE
Bug: navigating to an insights dashboard for a project causes a client-side exception making the page unusable

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/insights#1105]
### Describe the bug

Navigating to my insights project page, i.e. https://insights.opensauced.pizza/pages/nickytonline/95/dashboard, results in a blank screen with the message `Application error: a client-side exception has occurred (see the browser console for more information).`

### Steps to reproduce

1. Log into Insights
2. Navigate to your project's dashboard (assuming you have at least one project)
3. The page loads and flashes with the page contents then immediately renders a blank page with the error message `Application error: a client-side exception has occurred (see the browser console for more information).`

![CleanShot 2023-04-18 at 14 18 47](https://user-images.githubusercontent.com/833231/232868076-5ac10eaf-7f6f-456d-84a0-9226e823ffe6.png)

I haven't had time to dig into this yet. Also consider looking into React's [error boundaries](https://fa.reactjs.org/docs/error-boundaries.html) so the page still loads with the working UI (if it makes sense in this scenario).

Here's the errors in my console.

```
You are on the browser
_app-39376bdc81d24e31.js:6 You are on the browser
6framework-ce84985cd166733a.js:9 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lh (framework-ce84985cd166733a.js:9:46304)
    at i (framework-ce84985cd166733a.js:9:121161)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at oS (framework-ce84985cd166733a.js:9:94027)
    at x (framework-ce84985cd166733a.js:33:1373)
    at MessagePort.T (framework-ce84985cd166733a.js:33:1903)
lh @ framework-ce84985cd166733a.js:9
i @ framework-ce84985cd166733a.js:9
oO @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oF @ framework-ce84985cd166733a.js:9
oS @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
framework-ce84985cd166733a.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-ce84985cd166733a.js:9:120830)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oS (framework-ce84985cd166733a.js:9:94295)
    at x (framework-ce84985cd166733a.js:33:1373)
    at MessagePort.T (framework-ce84985cd166733a.js:33:1903)
i @ framework-ce84985cd166733a.js:9
oO @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oF @ framework-ce84985cd166733a.js:9
ox @ framework-ce84985cd166733a.js:9
oS @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
framework-ce84985cd166733a.js:9 TypeError: Cannot read properties of undefined (reading 'id')
    at y ([toolName]-ae1b98b1633a0bb4.js:1:2246)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
    at i (framework-ce84985cd166733a.js:9:120372)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oS (framework-ce84985cd166733a.js:9:94295)
    at x (framework-ce84985cd166733a.js:33:1373)
a5 @ framework-ce84985cd166733a.js:9
a.componentDidCatch.t.callback @ framework-ce84985cd166733a.js:9
lH @ framework-ce84985cd166733a.js:9
uY @ framework-ce84985cd166733a.js:9
e @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oS @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
main-947cbedfbf973616.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at y ([toolName]-ae1b98b1633a0bb4.js:1:2246)
    at ab (framework-ce84985cd166733a.js:9:60917)
    at ud (framework-ce84985cd166733a.js:9:72803)
    at i (framework-ce84985cd166733a.js:9:120372)
    at oO (framework-ce84985cd166733a.js:9:99114)
    at framework-ce84985cd166733a.js:9:98981
    at oF (framework-ce84985cd166733a.js:9:98988)
    at ox (framework-ce84985cd166733a.js:9:95740)
    at oS (framework-ce84985cd166733a.js:9:94295)
    at x (framework-ce84985cd166733a.js:33:1373)
en @ main-947cbedfbf973616.js:1
fn @ main-947cbedfbf973616.js:1
value @ main-947cbedfbf973616.js:1
a.componentDidCatch.t.callback @ framework-ce84985cd166733a.js:9
lH @ framework-ce84985cd166733a.js:9
uY @ framework-ce84985cd166733a.js:9
e @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oS @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
main-947cbedfbf973616.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
en @ main-947cbedfbf973616.js:1
fn @ main-947cbedfbf973616.js:1
value @ main-947cbedfbf973616.js:1
a.componentDidCatch.t.callback @ framework-ce84985cd166733a.js:9
lH @ framework-ce84985cd166733a.js:9
uY @ framework-ce84985cd166733a.js:9
e @ framework-ce84985cd166733a.js:9
(anonymous) @ framework-ce84985cd166733a.js:9
oI @ framework-ce84985cd166733a.js:9
oS @ framework-ce84985cd166733a.js:9
x @ framework-ce84985cd166733a.js:33
T @ framework-ce84985cd166733a.js:33
_a
```

### Affected services

insights.opensauced.pizza

### Platforms

Desktop

### Browsers

Other (add additional context)

### Environment

Production

### Additional context

I'm using the Arc browser (Chromium-based), but I don't think this is the issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Thanks @nickytonline. Does this happen in an incognito window also?

**Comment by nickytonline** [comment]
Good call. It works in incognito mode, so perhaps there is some residual state from a previous version?

![CleanShot 2023-04-18 at 14 47 39](https://user-images.githubusercontent.com/833231/232874371-6b6c56c8-b32c-4528-8bf1-eee38f8f94c0.png)

I went through local storage, sessions storage, and cookies deleting one by one and it looks like the Supabase auth token stored in the cookie `supabase-auth-token` was the culprit. Deleting that and refreshing the page fixed it (in regular browser window)

**Comment by brandonroberts** [comment]
Yea, I believe this was an issue with the cache. We'll look into better ways of clearing the cache on releases, and also better error handling with the error boundaries.  Thanks!
