### ISSUE TITLE
Bug: Error on `/user/[username]` route on some Mobile browsers

### ISSUE THREAD

**Issue by babblebey** [open-sauced/insights#1493]
### Describe the bug

On Visit to `user/[username]` route specifically on the Brave Browser Mobile, the error below occurs.

![Screenshot_2023-08-05-16-56-06-909_com brave browser](https://github.com/open-sauced/.github/assets/25631971/6227213f-3250-488b-a698-4365e5abbf15)

This has been the case for as long as I've been in the community, 1.5month+ now.

It work alright on `Chrome Mobile` browsers I have since tested on other browser I can reach on my mobile and here' are the results

- Chrome ⚪ Mobile - `Works` ✅
- Opera 🅾️ Mini - `Application Error` ❌
- Brave 🦁 Mobile - `Application Error` ❌ 
- Kiwi 🥝 Browser - `Application Error` ❌

### Steps to reproduce

On the browsers stated as ones with error.

1. Visit the highlights page at `/feed`
2. Click on any user profile which should route you to `/user/[username]`

### Expected Behaviour
The User Profile should be opened normally

### Actual Behaviour
The page opens to an error message `Application error: a client-side exception has occurred (see the browser console for more information).`

### Browsers

Opera, Other (add additional context)

### Additional context (Is this in dev or production?)

Brave Mobile, Kiwi, Opera Mini

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
Do you have any stacktrace information?

**Comment by babblebey** [comment]
> Do you have any stacktrace information?

None for now, I will have to figure out a way to access the `console` on the mobile browser to get that.

Will revert asap!

**Comment by babblebey** [comment]
Here @brandonroberts 

```shell
main-9025912cef66298b.js:1 - TypeError: J.pathname.split(...).at is not a function
    at eP (9055.30fa0038a7658f88.js:1:21330)
    at ab (framework-aec4381329cec0e4.js:9:60911)
    at i (framework-aec4381329cec0e4.js:9:119455)
    at oO (framework-aec4381329cec0e4.js:9:99104)
    at framework-aec4381329cec0e4.js:9:98971
    at oF (framework-aec4381329cec0e4.js:9:98978)
    at ox (framework-aec4381329cec0e4.js:9:95730)
    at oC (framework-aec4381329cec0e4.js:9:96119)
    at r4 (framework-aec4381329cec0e4.js:9:44772)
    at framework-aec4381329cec0e4.js:9:93622
```

```shell
main-9025912cef66298b.js:1 - A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

![image](https://github.com/open-sauced/insights/assets/25631971/ad2a45b4-0927-460a-b3b0-55954c54b493)

**Comment by brandonroberts** [comment]
Looks like its coming from here https://github.com/open-sauced/insights/blob/c4c56098826f085e5c551e088ac4fc3ada969f34/components/organisms/ContributorProfileTab/contributor-profile-tab.tsx#L67 

Could be a browser support issue
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Comment by takanome-dev** [comment]
I tried it using the devtools and my phone on Brave Browser but couldn't reproduce it :thinking: 

And I think it's pretty well supported, since Brave is chromium based it should work

![caniuse-at](https://github.com/open-sauced/insights/assets/79809121/9f57f19c-1bc7-40a2-bd1d-287bc2d2e6da)

**Comment by babblebey** [comment]
Hey @takanome-dev 

You will be needing to use `USB Debugging` with your Developer Mode turned on, on your Android device to starte with.

Learn More - https://www.browserstack.com/guide/chrome-mobile-debugging#toc0 

In regard the Chromium relation, I thought the same too, but it just doesn't happen to apply, I don't know why.

I will really want you to recreate the issue first, then we can try figure out how to use a polyfill for this or what best way to move forward.

**Comment by babblebey** [comment]
.take
